name: Frontend CI Pull request

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
on:
  pull_request:
    branches:
      - 'release/*'
      - 'refactor/*'
      - 'dev'
      - 'master'
jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@tenna-llc'
      - run: sudo apt-get update
      - run: git fetch --all
      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-package-lock-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-package-lock-cache-
      - run: npm i
      - run: npm test
      - run: npm run build
